// Seed data extracted from current static version
// This file contains all the data that will be seeded into the database

import { Utensils, Coffee } from "lucide-react";

export const SEED_CATEGORIES = [
  {
    id: "chicken_meals_rice",
    name_ar: "وجبات دجاج متبل مع الأرز",
    name_en: "Marinated Chicken Meals with Rice",
    name_fr: "Repas de Poulet Mariné avec Riz",
    icon_name: "Utensils",
    display_order: 1,
  },
  {
    id: "stews_sauces",
    name_ar: "المرق والصلصات",
    name_en: "Stews and Sauces",
    name_fr: "Ragoûts et Sauces",
    icon_name: "Utensils",
    display_order: 2,
  },
  {
    id: "additions_salads",
    name_ar: "الإضافات والسلطات",
    name_en: "Additions and Salads",
    name_fr: "Suppléments et Salades",
    icon_name: "Utensils",
    display_order: 3,
  },
  {
    id: "charcoal_sandwiches",
    name_ar: "سندويشات متبل عالفحم",
    name_en: "Charcoal Grilled Marinated Sandwiches",
    name_fr: "Sandwichs Marinés Grillés au Charbon",
    icon_name: "Utensils",
    display_order: 4,
  },
  {
    id: "rice",
    name_ar: "الأرز",
    name_en: "Rice",
    name_fr: "Riz",
    icon_name: "Utensils",
    display_order: 5,
  },
  {
    id: "drinks",
    name_ar: "المشروبات",
    name_en: "Drinks",
    name_fr: "Boissons",
    icon_name: "Coffee",
    display_order: 6,
  },
  {
    id: "mansaf",
    name_ar: "مناسف الدجاج بالمكسرات على صينية",
    name_en: "Chicken Mansaf with Nuts on a Tray",
    name_fr: "Mansaf de Poulet aux Noix sur Plateau",
    icon_name: "Utensils",
    display_order: 7,
  },
  {
    id: "stuffed_chicken",
    name_ar: "دجاج محشي بالكسكس مع الخضروات",
    name_en: "Stuffed Chicken with Couscous and Vegetables",
    name_fr: "Poulet Farci au Couscous avec Légumes",
    icon_name: "Utensils",
    display_order: 8,
  },
  {
    id: "pressure_grilled",
    name_ar: "دجاج متبل مشوي مضغوط",
    name_en: "Pressure Cooked Marinated Grilled Chicken",
    name_fr: "Poulet Mariné Grillé à Pression",
    icon_name: "Utensils",
    display_order: 9,
  },
  {
    id: "charcoal_marinated",
    name_ar: "دجاج عالفحم",
    name_en: "Chicken on Charcoal",
    name_fr: "Poulet sur Charbon",
    icon_name: "Utensils",
    display_order: 10,
  },
  {
    id: "charcoal_bbq",
    name_ar: "مشاوي دجاج عالفحم",
    name_en: "Charcoal Grilled Chicken BBQ",
    name_fr: "BBQ de Poulet Grillés au Charbon",
    icon_name: "Utensils",
    display_order: 11,
  },
  {
    id: "wings",
    name_ar: "أجنحة دجاج متبل",
    name_en: "Marinated Chicken Wings",
    name_fr: "Ailes de Poulet Marinées",
    icon_name: "Utensils",
    display_order: 12,
  },
  {
    id: "sumac_chicken",
    name_ar: "دجاج بالسماك عالفحم",
    name_en: "Chicken with Sumac on Charcoal",
    name_fr: "Poulet au Sumac sur Charbon",
    icon_name: "Utensils",
    display_order: 13,
  },
];

export const SEED_MENU_ITEMS = [
  // Category 1: وجبات دجاج متبل مع الأرز
  {
    category_id: "chicken_meals_rice",
    name_ar: "نفر مقلوبة دجاج",
    name_en: "Chicken Maqluba Portion",
    name_fr: "Portion Maqluba Poulet",
    description_ar: "طبق أرز – باذنجان – بصل – وفلفل – دجاج مشوي – صلصة – بصل",
    description_en: "Rice plate – Eggplant – Onion – and Pepper – Grilled Chicken – Sauce – Onion",
    description_fr: "Assiette de riz – Aubergine – Oignon – et Poivre – Poulet Grillé – Sauce – Oignon",
    price: 8000,
    display_order: 1,
  },
  {
    category_id: "chicken_meals_rice",
    name_ar: "وجبة دجاج بالكاري مع الأرز",
    name_en: "Chicken Curry Meal with Rice",
    name_fr: "Repas Curry Poulet avec Riz",
    description_ar: "طبق أرز – صلصة الكاري بالدجاج المشوي – ثومية – طرشي – خبز",
    description_en: "Rice plate – Curry sauce with grilled chicken – Garlic sauce – Pickles – Bread",
    description_fr: "Assiette de riz – Sauce Curry au Poulet Grillé – Sauce Ail – Cornichons – Pain",
    price: 7500,
    display_order: 2,
  },
  {
    category_id: "chicken_meals_rice",
    name_ar: "وجبة دجاج بالبطاطا والليمون",
    name_en: "Chicken with Potatoes and Lemon Meal",
    name_fr: "Repas Poulet avec Pommes de Terre et Citron",
    description_ar: "طبق أرز – دجاج – بطاطا – ليمون – ثومية – طرشي – خبز",
    description_en: "Rice plate – Chicken – Potatoes – Lemon – Garlic sauce – Pickles – Bread",
    description_fr: "Assiette de riz – Poulet – Pommes de terre – Citron – Sauce Ail – Cornichons – Pain",
    price: 7500,
    display_order: 3,
  },
  {
    category_id: "chicken_meals_rice",
    name_ar: "علبة السعادة",
    name_en: "Happiness Box",
    name_fr: "Boîte du Bonheur",
    description_ar: "دجاج مسحب – فطر – صلصة – جبن",
    description_en: "Pulled chicken – Mushroom – Sauce – Cheese",
    description_fr: "Poulet effiloché – Champignon – Sauce – Fromage",
    price: 6000,
    display_order: 4,
  },
  // Category 2: المرق والصلصات
  {
    category_id: "stews_sauces",
    name_ar: "مرقة الفاصوليا",
    name_en: "Bean Stew",
    name_fr: "Ragoût de Haricots",
    description_ar: "مرقة فاصوليا",
    description_en: "Bean stew",
    description_fr: "Ragoût de haricots",
    price: 1500,
    display_order: 1,
  },
  {
    category_id: "stews_sauces",
    name_ar: "مرقة الباذنجان",
    name_en: "Eggplant Stew",
    name_fr: "Ragoût d'Aubergine",
    description_ar: "مرقة باذنجان",
    description_en: "Eggplant stew",
    description_fr: "Ragoût d'aubergine",
    price: 2000,
    display_order: 2,
  },
  {
    category_id: "stews_sauces",
    name_ar: "صلصة البطاطا بالليمون",
    name_en: "Potato Sauce with Lemon",
    name_fr: "Sauce Pomme de Terre au Citron",
    description_ar: "صلصة البطاطا بالليمون",
    description_en: "Potato sauce with lemon",
    description_fr: "Sauce pomme de terre au citron",
    price: 2000,
    display_order: 3,
  },
  {
    category_id: "stews_sauces",
    name_ar: "صلصة الكاري",
    name_en: "Curry Sauce",
    name_fr: "Sauce Curry",
    description_ar: "صلصة الكاري",
    description_en: "Curry sauce",
    description_fr: "Sauce curry",
    price: 2000,
    display_order: 4,
  },
  {
    category_id: "stews_sauces",
    name_ar: "صلصة الفطر",
    name_en: "Mushroom Sauce",
    name_fr: "Sauce Champignons",
    description_ar: "صلصة الفطر",
    description_en: "Mushroom sauce",
    description_fr: "Sauce champignons",
    price: 2000,
    display_order: 5,
  },
  {
    category_id: "stews_sauces",
    name_ar: "شوربة الدجاج",
    name_en: "Chicken Soup",
    name_fr: "Soupe de Poulet",
    description_ar: "شوربة الدجاج",
    description_en: "Chicken soup",
    description_fr: "Soupe de poulet",
    price: 1000,
    display_order: 6,
  },
  // Category 3: الإضافات والسلطات
  {
    category_id: "additions_salads",
    name_ar: "صحن مقبلات صغير",
    name_en: "Small Appetizer Plate",
    name_fr: "Petite Assiette d'Apéritif",
    description_ar: "صحن مقبلات صغير",
    description_en: "Small appetizer plate",
    description_fr: "Petite assiette d'apéritif",
    price: 3000,
    display_order: 1,
  },
  {
    category_id: "additions_salads",
    name_ar: "صحن مقبلات مشكل",
    name_en: "Mixed Appetizer Plate",
    name_fr: "Assiette d'Apéritif Mixte",
    description_ar: "صحن مقبلات مشكل",
    description_en: "Mixed appetizer plate",
    description_fr: "Assiette d'apéritif mixte",
    price: 6000,
    display_order: 2,
  },
  {
    category_id: "additions_salads",
    name_ar: "حمص بطحينة",
    name_en: "Hummus with Tahini",
    name_fr: "Houmous au Tahini",
    description_ar: "حمص بطحينة",
    description_en: "Hummus with tahini",
    description_fr: "Houmous au tahini",
    price: 2000,
    display_order: 3,
  },
  {
    category_id: "additions_salads",
    name_ar: "سلطة خضراء بالنعناع",
    name_en: "Green Salad with Mint",
    name_fr: "Salade Verte à la Menthe",
    description_ar: "سلطة خضراء بالنعناع",
    description_en: "Green salad with mint",
    description_fr: "Salade verte à la menthe",
    price: 3000,
    display_order: 4,
  },
  {
    category_id: "additions_salads",
    name_ar: "علبة بطاطا",
    name_en: "Fries Box",
    name_fr: "Boîte de Frites",
    description_ar: "علبة بطاطا",
    description_en: "Fries box",
    description_fr: "Boîte de frites",
    price: 2000,
    display_order: 5,
  },
  {
    category_id: "additions_salads",
    name_ar: "حشوة",
    name_en: "Filling",
    name_fr: "Farce",
    description_ar: "مكسرات وشعيرية وبازليا وجزر",
    description_en: "Nut, vermicelli, pea, and carrot",
    description_fr: "aux noix, vermicelles, petits pois et carottes",
    price: 3000,
    display_order: 6,
  },
  {
    category_id: "additions_salads",
    name_ar: "إضافة مكسرات",
    name_en: "Add Nuts",
    name_fr: "Ajouter des Noix",
    description_ar: "إضافة مكسرات",
    description_en: "Add nuts",
    description_fr: "Ajouter des noix",
    price: 1000,
    display_order: 7,
  },
  // Category 4: سندويشات متبل عالفحم
  {
    category_id: "charcoal_sandwiches",
    name_ar: "صاج دجاج مسحب عالفحم",
    name_en: "Charcoal Pulled Chicken Saj",
    name_fr: "Saj Poulet Effiloché au Charbon",
    description_ar: "سندويش صاج دجاج مسحب مشوي عالفحم",
    description_en: "Pulled chicken saj sandwich grilled on charcoal",
    description_fr: "Sandwich Saj au poulet effiloché grillé au charbon",
    price: 4000,
    display_order: 1,
  },
  {
    category_id: "charcoal_sandwiches",
    name_ar: "صاج شيش طاووق",
    name_en: "Saj Shish Tawook",
    name_fr: "Saj Shish Taouk",
    description_ar: "صاج شيش طاووق",
    description_en: "Saj shish tawook",
    description_fr: "Saj shish taouk",
    price: 5000,
    display_order: 2,
  },
  {
    category_id: "charcoal_sandwiches",
    name_ar: "وجبة صاج دجاج مسحب عالفحم",
    name_en: "Saj Pulled Chicken on Charcoal Meal",
    name_fr: "Repas Saj Poulet Effiloché sur Charbon",
    description_ar: "شاش شيش طاووق مقطع – بطاطا – ثومية – طرشي – خبز – مخلل – سكر مع بسبس",
    description_en: "Cut shish tawook saj – Potatoes – Garlic sauce – Pickles – Bread – Pickles – Sugar with Pepsi",
    description_fr: "Saj shish taouk coupé – Pommes de terre – Sauce Ail – Cornichons – Pain – Cornichons – Sucre avec Pepsi",
    price: 6500,
    display_order: 3,
  },
  {
    category_id: "charcoal_sandwiches",
    name_ar: "وجبة صاج شيش طاووق",
    name_en: "Saj Shish Tawook Meal",
    name_fr: "Repas Saj Shish Taouk",
    description_ar: "نفس مكونات الوجبة السابقة مع تغيير نوع البروتين",
    description_en: "Same ingredients as previous meal with different protein type",
    description_fr: "Mêmes ingrédients que le repas précédent avec un type de protéine différent",
    price: 7500,
    display_order: 4,
  },
  // Category 5: الأرز
  {
    category_id: "rice",
    name_ar: "طبق أرز",
    name_en: "Rice Plate",
    name_fr: "Assiette de Riz",
    description_ar: "طبق أرز",
    description_en: "Rice plate",
    description_fr: "Assiette de riz",
    price: 2500,
    display_order: 1,
  },
  {
    category_id: "rice",
    name_ar: "صينية أرز وسط",
    name_en: "Medium Rice Tray",
    name_fr: "Plateau de Riz Moyen",
    description_ar: "صينية أرز وسط",
    description_en: "Medium rice tray",
    description_fr: "Plateau de riz moyen",
    price: 3500,
    display_order: 2,
  },
  {
    category_id: "rice",
    name_ar: "صينية أرز كبيرة",
    name_en: "Large Rice Tray",
    name_fr: "Grand Plateau de Riz",
    description_ar: "صينية أرز كبيرة",
    description_en: "Large rice tray",
    description_fr: "Grand plateau de riz",
    price: 5000,
    display_order: 3,
  },
  {
    category_id: "rice",
    name_ar: "وجبة أرز مع مرقتين",
    name_en: "Rice Meal with Two Stews",
    name_fr: "Repas Riz avec Deux Ragoûts",
    description_ar: "طبق أرز – نوعين مرق – ثومية – طرشي – حمص بطحينة",
    description_en: "Rice plate – Two types of stew – Garlic sauce – Pickles – Hummus",
    description_fr: "Assiette de riz – Deux sortes de ragoût – Sauce Ail – Cornichons – Houmous",
    price: 4000,
    display_order: 4,
  },
  // Category 6: المشروبات
  {
    category_id: "drinks",
    name_ar: "بيبسي – سفن – ميرندا – لبن",
    name_en: "Pepsi – 7UP – Miranda – Laban",
    name_fr: "Pepsi – 7UP – Miranda – Laban",
    description_ar: "بيبسي – سفن – ميرندا – لبن",
    description_en: "Pepsi – 7UP – Miranda – Laban",
    description_fr: "Pepsi – 7UP – Miranda – Laban",
    price: 750,
    display_order: 1,
  },
  {
    category_id: "drinks",
    name_ar: "ماء",
    name_en: "Water",
    name_fr: "Eau",
    description_ar: "ماء",
    description_en: "Water",
    description_fr: "Eau",
    price: 500,
    display_order: 2,
  },
  // Continue with remaining categories... (I'll add the rest in a continuation)
];

// Import and merge complete menu items
import { SEED_MENU_ITEMS_COMPLETE } from './menu-items-complete';

// Merge all menu items
export const SEED_MENU_ITEMS_ALL = [
  ...SEED_MENU_ITEMS,
  ...SEED_MENU_ITEMS_COMPLETE,
];

// Due to length, I'll create a separate file for the remaining items
// This is just the first portion to show structure

