// Complete menu items seed data - extracted from App.tsx
export const SEED_MENU_ITEMS_COMPLETE = [
  // Category: mansaf (continuing from previous)
  {
    category_id: "mansaf",
    name_ar: "منسف دجاجة مشوية صينية كبيرة",
    name_en: "Large Grilled Chicken Mansaf Tray",
    name_fr: "Grand Plateau Mansaf Poulet Grillé",
    description_ar: "دجاجة – صينية أرز كبيرة – شعيرية – مكسرات – مرق مشكل – بطاطا – ثومية – طرشي – خبز",
    description_en: "Chicken – Large rice tray – Vermicelli – Nuts – Mixed stew – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Poulet – Grand plateau de riz – Vermicelles – Noix – Ragoût mixte – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 27000,
    display_order: 1,
  },
  {
    category_id: "mansaf",
    name_ar: "منسف نصف دجاجة مشوية",
    name_en: "Half Grilled Chicken Mansaf",
    name_fr: "Mansaf Demi-Poulet Grillé",
    description_ar: "نصف دجاجة – صينية أرز – شعيرية – مكسرات – مرق مشكل – بطاطا – ثومية – طرشي – خبز",
    description_en: "Half chicken – Rice tray – Vermicelli – Nuts – Mixed stew – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Demi-poulet – Plateau de riz – Vermicelles – Noix – Ragoût mixte – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 16000,
    display_order: 2,
  },
  {
    category_id: "mansaf",
    name_ar: "منسف دجاجة محشية صينية كبيرة",
    name_en: "Large Stuffed Chicken Mansaf Tray",
    name_fr: "Grand Plateau Mansaf Poulet Farci",
    description_ar: "دجاجة محشية – صينية أرز كبيرة – شعيرية – مكسرات – مرق مشكل – بطاطا – ثومية – طرشي – خبز",
    description_en: "Stuffed chicken – Large rice tray – Vermicelli – Nuts – Mixed stew – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Poulet farci – Grand plateau de riz – Vermicelles – Noix – Ragoût mixte – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 30000,
    display_order: 3,
  },
  {
    category_id: "mansaf",
    name_ar: "منسف نصف دجاجة محشية بالكسكس",
    name_en: "Half Stuffed Chicken Mansaf with Couscous",
    name_fr: "Mansaf Demi-Poulet Farci au Couscous",
    description_ar: "نصف دجاجة محشية – شعيرية – مكسرات – صلصات – مرق مشكل – بطاطا – ثومية – طرشي – خبز",
    description_en: "Half stuffed chicken – Vermicelli – Nuts – Sauces – Mixed stew – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Demi-poulet farci – Vermicelles – Noix – Sauces – Ragoût mixte – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 17000,
    display_order: 4,
  },
  {
    category_id: "mansaf",
    name_ar: "منسف دجاجة عالفحم (8 قطع)",
    name_en: "Charcoal Chicken Mansaf (8 pieces)",
    name_fr: "Mansaf Poulet au Charbon (8 pièces)",
    description_ar: "نص دجاجة – أرز – شعيرية – مكسرات – مرق مشكل – بطاطا – ثومية – طرشي – خبز",
    description_en: "Half chicken – Rice – Vermicelli – Nuts – Mixed stew – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Demi-poulet – Riz – Vermicelles – Noix – Ragoût mixte – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 27000,
    display_order: 5,
  },
  {
    category_id: "mansaf",
    name_ar: "منسف نصف دجاجة عالفحم (4 قطع)",
    name_en: "Half Charcoal Chicken Mansaf (4 pieces)",
    name_fr: "Mansaf Demi-Poulet au Charbon (4 pièces)",
    description_ar: "نفس المكونات بحجم أصغر",
    description_en: "Same ingredients in smaller size",
    description_fr: "Mêmes ingrédients en taille plus petite",
    price: 16000,
    display_order: 6,
  },
  // Category: pressure_grilled
  {
    category_id: "pressure_grilled",
    name_ar: "دجاجة مشوية كاملة",
    name_en: "Whole Grilled Chicken",
    name_fr: "Poulet Grillé Entier",
    description_ar: "دجاجة – رز – شعيرية – بطاطا – ثومية – طرشي – خبز",
    description_en: "Chicken – Rice – Vermicelli – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Poulet – Riz – Vermicelles – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 17000,
    display_order: 1,
  },
  {
    category_id: "pressure_grilled",
    name_ar: "نصف دجاجة مشوية",
    name_en: "Half Grilled Chicken",
    name_fr: "Demi-Poulet Grillé",
    description_ar: "نصف دجاجة – رز – شعيرية – بطاطا – ثومية – طرشي – خبز",
    description_en: "Half chicken – Rice – Vermicelli – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Demi-poulet – Riz – Vermicelles – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 9000,
    display_order: 2,
  },
  {
    category_id: "pressure_grilled",
    name_ar: "ربع دجاجة مشوية",
    name_en: "Quarter Grilled Chicken",
    name_fr: "Quart de Poulet Grillé",
    description_ar: "ربع دجاجة مشوية",
    description_en: "Quarter grilled chicken",
    description_fr: "Quart de poulet grillé",
    price: 6500,
    display_order: 3,
  },
  {
    category_id: "pressure_grilled",
    name_ar: "دجاجة مشوية كاملة مع الأرز",
    name_en: "Whole Grilled Chicken with Rice",
    name_fr: "Poulet Grillé Entier avec Riz",
    description_ar: "دجاجة مشوية كاملة مع الأرز",
    description_en: "Whole grilled chicken with rice",
    description_fr: "Poulet grillé entier avec riz",
    price: 20000,
    display_order: 4,
  },
  {
    category_id: "pressure_grilled",
    name_ar: "نصف دجاجة مشوية مع الأرز",
    name_en: "Half Grilled Chicken with Rice",
    name_fr: "Demi-Poulet Grillé avec Riz",
    description_ar: "نصف دجاجة مشوية مع الأرز",
    description_en: "Half grilled chicken with rice",
    description_fr: "Demi-poulet grillé avec riz",
    price: 11000,
    display_order: 5,
  },
  {
    category_id: "pressure_grilled",
    name_ar: "ربع دجاجة مشوية مع الأرز",
    name_en: "Quarter Grilled Chicken with Rice",
    name_fr: "Quart de Poulet Grillé avec Riz",
    description_ar: "ربع دجاجة مشوية مع الأرز",
    description_en: "Quarter grilled chicken with rice",
    description_fr: "Quart de poulet grillé avec riz",
    price: 6500,
    display_order: 6,
  },
  // Category: charcoal_marinated
  {
    category_id: "charcoal_marinated",
    name_ar: "دجاجة عالفحم كاملة",
    name_en: "Whole Chicken on Charcoal",
    name_fr: "Poulet Entier sur Charbon",
    description_ar: "دجاجة عالفحم كاملة (8 قطع)",
    description_en: "Whole chicken on charcoal (8 pieces)",
    description_fr: "Poulet entier sur charbon (8 pièces)",
    price: 17000,
    display_order: 1,
  },
  {
    category_id: "charcoal_marinated",
    name_ar: "نصف دجاجة عالفحم",
    name_en: "Half Chicken on Charcoal",
    name_fr: "Demi-Poulet sur Charbon",
    description_ar: "نصف دجاجة عالفحم (4 قطع)",
    description_en: "Half chicken on charcoal (4 pieces)",
    description_fr: "Demi-poulet sur charbon (4 pièces)",
    price: 9000,
    display_order: 2,
  },
  {
    category_id: "charcoal_marinated",
    name_ar: "ربع دجاجة عالفحم",
    name_en: "Quarter Chicken on Charcoal",
    name_fr: "Quart de Poulet sur Charbon",
    description_ar: "ربع دجاجة عالفحم",
    description_en: "Quarter chicken on charcoal",
    description_fr: "Quart de poulet sur charbon",
    price: 6500,
    display_order: 3,
  },
  {
    category_id: "charcoal_marinated",
    name_ar: "دجاجة عالفحم مع الأرز",
    name_en: "Chicken on Charcoal with Rice",
    name_fr: "Poulet sur Charbon avec Riz",
    description_ar: "دجاجة عالفحم مع الأرز (8 قطع)",
    description_en: "Chicken on charcoal with rice (8 pieces)",
    description_fr: "Poulet sur charbon avec riz (8 pièces)",
    price: 20000,
    display_order: 4,
  },
  {
    category_id: "charcoal_marinated",
    name_ar: "نصف دجاجة عالفحم مع الأرز",
    name_en: "Half Chicken on Charcoal with Rice",
    name_fr: "Demi-Poulet sur Charbon avec Riz",
    description_ar: "نصف دجاجة عالفحم مع الأرز (4 قطع)",
    description_en: "Half chicken on charcoal with rice (4 pieces)",
    description_fr: "Demi-poulet sur charbon avec riz (4 pièces)",
    price: 11000,
    display_order: 5,
  },
  // Category: charcoal_bbq
  {
    category_id: "charcoal_bbq",
    name_ar: "وجبة شيش طاووق",
    name_en: "Shish Tawook Meal",
    name_fr: "Repas Shish Taouk",
    description_ar: "يقدم مع أرز أو بطاطا، ثومية، طرشي، خبز",
    description_en: "Served with rice or potatoes, garlic sauce, pickles, bread",
    description_fr: "Servi avec riz ou pommes de terre, sauce à l'ail, cornichons, pain",
    price: 7500,
    display_order: 1,
  },
  {
    category_id: "charcoal_bbq",
    name_ar: "كيلو شيش طاووق",
    name_en: "Kilo Shish Tawook",
    name_fr: "Kilo Shish Taouk",
    description_ar: "كيلو شيش طاووق",
    description_en: "Kilo shish tawook",
    description_fr: "Kilo shish taouk",
    price: 18500,
    display_order: 2,
  },
  {
    category_id: "charcoal_bbq",
    name_ar: "كيلو أجنحة مع شيش طاووق",
    name_en: "Kilo Wings with Shish Tawook",
    name_fr: "Kilo Ailes avec Shish Taouk",
    description_ar: "كيلو أجنحة مع شيش طاووق",
    description_en: "Kilo wings with shish tawook",
    description_fr: "Kilo ailes avec shish taouk",
    price: 18500,
    display_order: 3,
  },
  // Category: stuffed_chicken
  {
    category_id: "stuffed_chicken",
    name_ar: "دجاجة محشية كاملة",
    name_en: "Whole Stuffed Chicken",
    name_fr: "Poulet Farci Entier",
    description_ar: "دجاجة محشية + ثومية + بطاطا + طرشي + خبز",
    description_en: "Stuffed chicken + Garlic sauce + Potatoes + Pickles + Bread",
    description_fr: "Poulet farci + Sauce Ail + Pommes de terre + Cornichons + Pain",
    price: 20000,
    display_order: 1,
  },
  {
    category_id: "stuffed_chicken",
    name_ar: "نصف دجاجة محشية",
    name_en: "Half Stuffed Chicken",
    name_fr: "Demi-Poulet Farci",
    description_ar: "نصف دجاجة محشية + ثومية + بطاطا + طرشي + خبز",
    description_en: "Half stuffed chicken + Garlic sauce + Potatoes + Pickles + Bread",
    description_fr: "Demi-poulet farci + Sauce Ail + Pommes de terre + Cornichons + Pain",
    price: 11000,
    display_order: 2,
  },
  // Category: wings
  {
    category_id: "wings",
    name_ar: "أجنحة مشوية سادة",
    name_en: "Plain Grilled Wings",
    name_fr: "Ailes Grillées Nature",
    description_ar: "أجنحة مشوية سادة",
    description_en: "Plain grilled wings",
    description_fr: "Ailes grillées nature",
    price: 6000,
    display_order: 1,
  },
  {
    category_id: "wings",
    name_ar: "أجنحة مشوية مع أرز",
    name_en: "Grilled Wings with Rice",
    name_fr: "Ailes Grillées avec Riz",
    description_ar: "أجنحة مشوية مع أرز",
    description_en: "Grilled wings with rice",
    description_fr: "Ailes grillées avec riz",
    price: 7000,
    display_order: 2,
  },
  {
    category_id: "wings",
    name_ar: "أجنحة مشوية بالباربكيو",
    name_en: "BBQ Grilled Wings",
    name_fr: "Ailes Grillées BBQ",
    description_ar: "أجنحة مشوية بالباربكيو",
    description_en: "BBQ grilled wings",
    description_fr: "Ailes grillées BBQ",
    price: 6500,
    display_order: 3,
  },
  // Category: sumac_chicken
  {
    category_id: "sumac_chicken",
    name_ar: "دجاجة عالفحم بالسمّاك",
    name_en: "Chicken on Charcoal with Sumac",
    name_fr: "Poulet sur Charbon au Sumac",
    description_ar: "دجاجة عالفحم – سماك – بطاطا – ثومية – طرشي – خبز",
    description_en: "Chicken on charcoal – Sumac – Potatoes – Garlic sauce – Pickles – Bread",
    description_fr: "Poulet sur charbon – Sumac – Pommes de terre – Sauce Ail – Cornichons – Pain",
    price: 20000,
    display_order: 1,
  },
  {
    category_id: "sumac_chicken",
    name_ar: "نصف دجاجة عالفحم بالسماك",
    name_en: "Half Chicken on Charcoal with Sumac",
    name_fr: "Demi-Poulet sur Charbon au Sumac",
    description_ar: "نصف دجاجة عالفحم بالسماك",
    description_en: "Half chicken on charcoal with sumac",
    description_fr: "Demi-poulet sur charbon au sumac",
    price: 11000,
    display_order: 2,
  },
];

